-- MySQL Script generated by MySQL Workbench
-- jeu. 10 déc. 2015 21:35:40 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SupTrips
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SupTrips
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SupTrips` DEFAULT CHARACTER SET utf8 ;
USE `SupTrips` ;

-- -----------------------------------------------------
-- Table `SupTrips`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SupTrips`.`Users` (
  `idbooster` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `firstname` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `lastname` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `campus_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `passwordl` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idbooster`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `SupTrips`.`Trips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SupTrips`.`Trips` (
  `idtrip` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `depart_date` DATE NULL DEFAULT NULL COMMENT '',
  `arrive_date` DATE NULL DEFAULT NULL COMMENT '',
  `depart_campus` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `arrive_campus` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Users_idbooster` INT NOT NULL COMMENT '',
  `airport_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idtrip`, `Users_idbooster`)  COMMENT '',
  INDEX `fk_Trips_Users_idx` (`Users_idbooster` ASC)  COMMENT '',
  CONSTRAINT `fk_Trips_Users`
    FOREIGN KEY (`Users_idbooster`)
    REFERENCES `SupTrips`.`Users` (`idbooster`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
